FROM node:18 as builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install --only=production

COPY prisma ./prisma/

RUN npx prisma generate

COPY . .

RUN npm run build

FROM node:18

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/package.json ./package.json

EXPOSE 3000

CMD ["node", "dist/main.js"]
