version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        ports:
            - "8080:3000"
        env_file:
            - .testing.env
    postgres:
        image: postgres:10.4
        ports:
            - "35000:5432"
        environment: 
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db